project_id = "koymmvuhcxlvcuoyjnvv"

[functions.generate-cv-summary]
verify_jwt = true

[functions.check-rate-limit]
verify_jwt = true

[functions.publish-scheduled-posts]
verify_jwt = true

[functions.send-email-notification]
verify_jwt = true

[functions.admin-user-actions]
verify_jwt = false

[functions.partners]
verify_jwt = false

[functions.seed-locations-de]
verify_jwt = false
